name: pr_test_code
on:
  pull_request_target:
      branches: [main,develop]
      types: [labeled]
jobs:
  build:
    name: test
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.labels.*.name, 'safe to test')
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{github.event.pull_request.base.sha}}
      - uses: actions/setup-python@v2
        with:
          python-version: "3.10.6"
      - run: pip install -r requirements.txt
      - run: python project_setting.py ${{secrets.ER_API_KEY}}
      - run: python -m unittest.py
